spring:
  datasource:
    username: root
    password: 141199
    url: jdbc:mysql://localhost:3306/major_project
    driver-class-name: com.mysql.cj.jdbc.Driver
   
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  
server:
  port: 9081
  