server:
  port: 8082
 
spring:
  application:
    name: WELCOME-API
  boot:
    admin:
      client:
        url: http://localhost:1111/
     
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
        
        